### ISSUE TITLE
插件编译不通过呀

### ISSUE THREAD

**Issue by tangjiemian** [JiangJuHong/FlutterQiniucloudLivePlugin#1]

**Comment by JiangJuHong** [comment]
你好，你可以通过 ``git clone `` 方式下载源代码，运行 example 模块查看案例，该版本现在不支持 ios，预计在一段时间后提供支持。

**Comment by tangjiemian** [comment]
android 的也没有编译通过

**Comment by JiangJuHong** [comment]
能不能提供一下错误信息，供排查使用

**Comment by tangjiemian** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "蒋具宏"<notifications@github.com&gt;; 
发送时间: 2019年12月17日(星期二) 中午1:40
收件人: "JiangJuHong/FlutterQiniucloudLivePlugin"<FlutterQiniucloudLivePlugin@noreply.github.com&gt;; 
抄送: "小飞船"<751585085@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [JiangJuHong/FlutterQiniucloudLivePlugin] 插件编译不通过呀 (#1)




能不能提供一下错误信息，供排查使用

**Comment by tangjiemian** [comment]
D:\AndroidGameWork\FlutterGithub\tangstudy\FlutterQiniucloudLivePlugin\android\src\main\java\top\huic\flutter_qiniucloud_live_plugin\FlutterQiniucloudLivePlugin.java:49: ����: �Ҳ�������
        channel.setMethodCallHandler(new FlutterQiniucloudLivePlugin(flutterPluginBinding.getBinaryMessenger(), flutterPluginBinding.getApplicationContext(), channel, flutterPluginBinding.getPlatformViewRegistry()));
                                                                                         ^
  ����:   ���� getBinaryMessenger()
  λ��: ����ΪFlutterPluginBinding�ı�� flutterPluginBinding
D:\AndroidGameWork\FlutterGithub\tangstudy\FlutterQiniucloudLivePlugin\android\src\main\java\top\huic\flutter_qiniucloud_live_plugin\FlutterQiniucloudLivePlugin.java:49: ����: �Ҳ�������
        channel.setMethodCallHandler(new FlutterQiniucloudLivePlugin(flutterPluginBinding.getBinaryMessenger(), flutterPluginBinding.getApplicationContext(), channel, flutterPluginBinding.getPlatformViewRegistry()));
                                                                                                                                                                                           ^
  ����:   ���� getPlatformViewRegistry()
  λ��: ����ΪFlutterPluginBinding�ı�� flutterPluginBinding 
--------------------------------
  随便请教个问题，编译日志乱码怎么解决

**Comment by JiangJuHong** [comment]
我不清楚你的运行环境，无法提供有效的帮助，建议你检查IDE以及项目的编码设置。

**Comment by JiangJuHong** [comment]
我已经检查了 example ，发现它确实无法运行，现在已经将它修复好，你可以重新 clone 项目，并尝试编译。如果你需要将该项目集成到你已有的Flutter项目，建议在未发行版本之前，Ref填写对应提交ID。
```
flutter_qiniucloud_live_plugin:
    git:
      url: https://github.com/JiangJuHong/FlutterQiniucloudLivePlugin.git
      ref: xxxxxxxxxxx
```

**Comment by tangjiemian** [comment]
好的，谢谢

**Comment by tangjiemian** [comment]
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.535], locale zh-CN)
    • Flutter version 1.9.1+hotfix.2 at E:\Environment\flutter\flutter
    • Framework revision 2d2a1ffec9 (3 months ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at E:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = E:\AndroidSDK
    • ANDROID_SDK_ROOT = E:\AndroidSDK
    • Java binary at: E:\Developtools\android-studio3.4\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at E:\Developtools\android-studio3.4\android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • BND AL10 • A5RNW18A11001199 • android-arm64 • Android 8.0.0 (API 26)
-------------------------------
修复了那两个镜像函数，我的环境是上面的，编译不能通过

**Comment by JiangJuHong** [comment]
可以提供一下报错信息吗？在我的电脑上，修改后 example 能够编译通过并正常运行
