### ISSUE TITLE
你好，请问这个可以用在实际项目中吗？能推流到腾讯或者阿里吗？还是只能使用七牛的服务？

### ISSUE THREAD

**Issue by cheaprYang** [JiangJuHong/FlutterQiniucloudLivePlugin#2]

**Comment by JiangJuHong** [comment]
你好，目前只支持七牛云，且当前是测试阶段，可以接入项目，但请随时关注最新版本



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: @cheapr <notifications@github.com&gt;
发送时间: 2020年3月11日 21:06
收件人: JiangJuHong/FlutterQiniucloudLivePlugin <FlutterQiniucloudLivePlugin@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[JiangJuHong/FlutterQiniucloudLivePlugin] 你好，请问这个可以用在实际项目中吗？能推流到腾讯或者阿里吗？还是只能使用七牛的服务？ (#2)
