### ISSUE TITLE
兄弟,幸苦了

### ISSUE THREAD

**Issue by pslxx** [JiangJuHong/FlutterQiniucloudLivePlugin#3]
水一下
我自己也正准备整合腾讯的移动直播SDK,我看你都写了,不知道这个中间可有什么坑

这个七牛的我从官方下下载的安卓demo,开播之后直接卡死.不知道是什么情况,不知道你可遇到过

**Comment by pslxx** [comment]
看了资料才发现,原来是技术型老板,厉害~ 而且好像公司对flutter研究的特别多.

**Comment by JiangJuHong** [comment]
七牛云直播最大的坑是部分代码Android和IOS不兼容，所以在状态这里我处理的办法就是保留了一些重要的状态。相比较七牛云，我使用腾讯云的RTC和IM时，发现Android和IOS能够很好的兼容，只会有小部分差异性。另外就是腾讯云直播的插件，你可以看看我发布的，目前 [FlutterTencentRtcPlugin](https://github.com/JiangJuHong/FlutterTencentRtcPlugin)，目前支持基本的RTC通信，但是对直播还没有提供支持@pslxx
