### ISSUE TITLE
无法推流

### ISSUE THREAD

**Issue by zhai3711** [JiangJuHong/FlutterQiniucloudLivePlugin#7]
09-18 15:33:25.333 29072-29072/top.huic.flutter_qiniucloud_live_plugin_example E/AppPara: context is not activity,can not set setScreenOrientation
09-18 15:33:25.369 29072-29072/top.huic.flutter_qiniucloud_live_plugin_example E/YOUME: Init: Already initialzed
09-18 15:33:25.369 29072-29072/top.huic.flutter_qiniucloud_live_plugin_example E/PLDroidRTCStreaming: RTC-Session:MeetingSession:failed to initialize engine, error code: -7
09-18 15:33:40.808 29072-29072/top.huic.flutter_qiniucloud_live_plugin_example E/MethodChannel#flutter/platform_views: Failed to handle method call
    java.lang.IllegalArgumentException: Only support 16:9/4:3 ratio!
        at com.qiniu.pili.droid.streaming.StreamingProfile.getVideoEncodingSize(StreamingProfile.java:1282)
        at com.qiniu.pili.droid.rtcstreaming.RTCMediaStreamingManager.prepare(RTCMediaStreamingManager.java:375)
        at top.huic.flutter_qiniucloud_live_plugin.view.QiniucloudPushPlatformView.init(QiniucloudPushPlatformView.java:294)
        at top.huic.flutter_qiniucloud_live_plugin.view.QiniucloudPushPlatformView.create(QiniucloudPushPlatformView.java:215)
        at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:174)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:419)
        at android.app.Dialog.show(Dialog.java:320)
        at android.app.Presentation.show(Presentation.java:235)
        at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:93)
        at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:53)
        at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:105)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)

**Comment by JiangJuHong** [comment]
请提供设备信息，以及复现步骤

**Comment by zhai3711** [comment]
努比亚 Z11  android6.0.1版本  骁龙820处理器  点开始推流之后空白,  状态一直是等待预览

**Comment by JiangJuHong** [comment]
请确认给予相机、麦克风等权限

**Comment by zhai3711** [comment]
有权限的

**Comment by zhai3711** [comment]
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Debug service listening on ws://127.0.0.1:59081/vOYSXbxMtfI=/ws
Syncing files to device NX531J...
I/PLDroidMediaStreaming(11173): Pili-Interface:MediaStreamingManager:created, AVCodecType = SW_VIDEO_WITH_SW_AUDIO_CODEC
I/PLDroidMediaStreaming(11173): Pili-System:MediaStreamingManager:{"device_model":"nubiaNX531J","os_version":"os version:6.0.1, Android SDK_INT:23, SoC Hardware:qcom","sdk_version":"librtmp-1.1.0;PLDroidCameraStreaming-2.3.0.5","app_name":"top.huic.flutter_qiniucloud_live_plugin_example","app_version":"1.0","gl_version":3}
I/PLDroidRTCStreaming(11173): RTC-Interface:RTCMediaStreaming:create RTCMediaStreamingManager encodingType = SW_VIDEO_WITH_SW_AUDIO_CODEC
I/PLDroidMediaStreaming(11173): Pili-Interface:MediaStreamingManager:setStreamingSessionListener true
I/PLDroidMediaStreaming(11173): Pili-Interface:MediaStreamingManager:setStreamStatusCallback true
I/PLDroidRTCStreaming(11173): RTC-Interface:RTCMediaStreaming:setConferenceOptions
I/PLDroidRTCStreaming(11173): RTC-Session:MeetingSession:setConferenceOptions +
I/PLDroidRTCStreaming(11173): RTC-Session:MeetingSession:setConferenceOptions -
I/PLDroidRTCStreaming(11173): RTC-Interface:RTCMediaStreaming:prepare
I/PLDroidMediaStreaming(11173): Pili-Interface:MediaStreamingManager:setStreamingStateListener true
I/PLDroidMediaStreaming(11173): Pili-Interface:MediaStreamingManager:setStreamingPreviewCallback true
W/PLDroidMediaStreaming(11173): Pili-Capture:CameraManager:mCamera is null in preparePreviewCallback
I/PLDroidMediaStreaming(11173): Pili-Interface:MediaStreamingManager:setAudioSourceCallback true
E/MethodChannel#flutter/platform_views(11173): Failed to handle method call
E/MethodChannel#flutter/platform_views(11173): java.lang.IllegalArgumentException: Only support 16:9/4:3 ratio!
E/MethodChannel#flutter/platform_views(11173): 	at com.qiniu.pili.droid.streaming.StreamingProfile.getVideoEncodingSize(StreamingProfile.java:1282)
E/MethodChannel#flutter/platform_views(11173): 	at com.qiniu.pili.droid.rtcstreaming.RTCMediaStreamingManager.prepare(RTCMediaStreamingManager.java:375)
E/MethodChannel#flutter/platform_views(11173): 	at top.huic.flutter_qiniucloud_live_plugin.view.QiniucloudPushPlatformView.init(QiniucloudPushPlatformView.java:294)
E/MethodChannel#flutter/platform_views(11173): 	at top.huic.flutter_qiniucloud_live_plugin.view.QiniucloudPushPlatformView.create(QiniucloudPushPlatformView.java:215)
E/MethodChannel#flutter/platform_views(11173): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:174)
E/MethodChannel#flutter/platform_views(11173): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:419)
E/MethodChannel#flutter/platform_views(11173): 	at android.app.Dialog.show(Dialog.java:320)
E/MethodChannel#flutter/platform_views(11173): 	at android.app.Presentation.show(Presentation.java:235)
E/MethodChannel#flutter/platform_views(11173): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:93)
E/MethodChannel#flutter/platform_views(11173): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:53)
E/MethodChannel#flutter/platform_views(11173): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:105)
E/MethodChannel#flutter/platform_views(11173): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/MethodChannel#flutter/platform_views(11173): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MethodChannel#flutter/platform_views(11173): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#flutter/platform_views(11173): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#flutter/platform_views(11173): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#flutter/platform_views(11173): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(11173): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#flutter/platform_views(11173): 	at android.os.Looper.loop(Looper.java:140)
E/MethodChannel#flutter/platform_views(11173): 	at android.app.ActivityThread.main(ActivityThread.java:5760)
E/MethodChannel#flutter/platform_views(11173): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(11173): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/MethodChannel#flutter/platform_views(11173): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
W/ResourceType(11173): No known package when getting name for resource number 0xffffffff
I/EglRenderer(11173): setLayoutAspectRatio: 1.0
I/SurfaceViewRenderer(11173): SurfaceViewRender:com.qiniu.pili.droid.rtcstreaming.RTCSurfaceView{8041f6 V.E...... ......ID 0,0-300,300}view width:300 height:300
I/SurfaceViewRenderer(11173): surfaceCreated
I/SurfaceViewRenderer(11173): surfaceChanged: format: 4 size: 300x300
I/EglRenderer(11173): setLayoutAspectRatio: 1.0
I/SurfaceViewRenderer(11173): SurfaceViewRender:com.qiniu.pili.droid.rtcstreaming.RTCSurfaceView{8041f6 V.E...... ......I. 0,0-300,300}view width:300 height:300
E/flutter (11173): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Only support 16:9/4:3 ratio!, null)
E/flutter (11173): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (11173): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (11173): <asynchronous suspension>
E/flutter (11173): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter (11173): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (11173): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (11173): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (11173): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter (11173): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #9      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (11173): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #11     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter (11173): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #13     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (11173): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #15     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
E/flutter (11173): #16     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter (11173): #17     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
E/flutter (11173): #18     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
E/flutter (11173): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #23     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
E/flutter (11173): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #39     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3166:14)
E/flutter (11173): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #41     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (11173): #42     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
E/flutter (11173): #43     PipelineOwner.flushLayout (package:flutter/src/render
E/flutter (11173): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'addRemoteWindow' was called on null.
E/flutter (11173): Receiver: null
E/flutter (11173): Tried calling: addRemoteWindow(id: 1)
E/flutter (11173): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (11173): #1      PushPageState.onPlayerViewCreated (package:flutter_qiniucloud_live_plugin_example/page/push.dart:269:16)
E/flutter (11173): #2      QiniucloudConnectPlayerViewState._onPlatformViewCreated (package:flutter_qiniucloud_live_plugin/view/qiniucloud_connected_player_view.dart:44:14)
E/flutter (11173): #3      AndroidViewController._create (package:flutter/src/services/platform_views.dart:643:15)
E/flutter (11173): <asynchronous suspension>
E/flutter (11173): #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (11173): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (11173): #6      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (11173): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter (11173): #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #10     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter (11173): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #12     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:544:15)
E/flutter (11173): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #14     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter (11173): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #16     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (11173): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #18     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
E/flutter (11173): #19     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter (11173): #20     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
E/flutter (11173): #21     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
E/flutter (11173): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #26     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
E/flutter (11173): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (11173): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (11173): #42     RenderOffstage.performLa

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during paint():
The getter 'width' was called on null.
Receiver: null
Tried calling: width

The relevant error-causing widget was: 
  AndroidView file:///C:/Users/Amy/Desktop/FlutterQiniucloudLivePlugin-master/lib/view/qiniucloud_connected_player_view.dart:27:14
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      RenderAndroidView.paint (package:flutter/src/rendering/platform_view.dart:192:46)
#2      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
#3      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
#4      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)

**Comment by JiangJuHong** [comment]
尝试通过 AndroidStudio 打开 example/android 目录，然后等待构建完成后再尝试运行，如果依旧不行，请卸载APP并重新走git拉取代码

**Comment by zhai3711** [comment]
还是不行的

**Comment by JiangJuHong** [comment]
#5 有同样的错误，参考：
![image](https://user-images.githubusercontent.com/17740963/93600000-9aeed780-f9f1-11ea-9e6a-775f0cd6cbb0.png)

**Comment by JiangJuHong** [comment]
我稍后将发布新版本，你可在新版本查看

**Comment by JiangJuHong** [comment]
如果没有其它疑问，我将关闭此 Issues
