### ISSUE TITLE
运行ios失败

### ISSUE THREAD

**Issue by youtengli** [JiangJuHong/FlutterQiniucloudLivePlugin#8]
您好， 我尝试clone并运行了example到我的实机上
- iphone7+ , ios 15.4.1
- Version 13.3 (13E113)

Error (Xcode):
'/Users/liyouteng/Documents/projects/FlutterQiniucloudLivePlugin/example/ios/Pod
s/PLRTCStreamingKit/Pod/Library/PLRTCStreamingKit.framework/PLRTCStreamingKit'
does not contain bitcode. You must rebuild it with bitcode enabled (Xcode
setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable
bitcode for this target. 
file '/Users/liyouteng/Documents/projects/FlutterQiniucloudLivePlugin/example/ios/Pod
s/PLRTCStreamingKit/Pod/Library/PLRTCStreamingKit.framework/PLRTCStreamingKit'
for architecture armv7

Encountered error while building for device.

尝试将PLRTCStreamingKit 下的 Build Settings -> Build Options -> Enable Bitcode 设定yes 或是no
都会得到这个错误

**Comment by JiangJuHong** [comment]
可能是Flutter 升级后导致的问题，五一后我会开始重构 / 优化代码，到时候就能运行起来了

**Comment by JiangJuHong** [comment]
已修复，请引入最新版本，并根据文档设置： ``config.build_settings['ENABLE_BITCODE'] = 'NO'``
